swagger: '2.0'
info:
  title: Post API
  description: API for Posts Microservice
  version: 1.0.0

host: "posts-3b5jwuffyri0g.apigateway.project-416223.cloud.goog"
basePath: /v1
schemes:
  - https
security:
  - api_key: ["AIzaSyA90DkUvaQr6b_KHEWsksJ6PfCX-oidIM8"]

paths:
  /posts/getMany:
    get:
      summary: Get all Posts
      description: Retrieve a list of all posts
      responses:
        '200':
          description: A list of posts
          schema:
            type: array
            items:
              $ref: '#/definitions/Post'
  /posts/getManyById/{teacherId}:
    get:
      summary: Get all Posts of a teacher
      description: Retrieve a list of all posts of a specific teacher
      parameters:
        - name: teacherId
          in: path
          description: ID of the teacher
          required: true
          type: integer
      responses:
        '200':
          description: A list of posts
          schema:
            type: array
            items:
              $ref: '#/definitions/Post'
  /posts/getCommentsById/{postId}:
    get:
      summary: Get all comments of a post
      description: Retrieve a list of all comments of a specific post
      parameters:
        - name: postId
          in: path
          description: ID of the post
          required: true
          type: integer
      responses:
        '200':
          description: A list of comments
          schema:
            type: array
            items:
              $ref: '#/definitions/Comment'
  /posts/{postId}:
    get:
      summary: Get post by Id
      description: Retrieve a post by its ID
      parameters:
        - name: postId
          in: path
          description: ID of the post
          required: true
          type: integer
      responses:
        '200':
          description: A single post
          schema:
            $ref: '#/definitions/Post'
  /posts/{postId}/addComment:
    post:
      summary: Create a comment
      description: Create a new comment for a post
      parameters:
        - name: postId
          in: path
          description: ID of the post
          required: true
          type: integer
      responses:
        '200':
          description: Comment created successfully
  /posts/{postId}/editComment/{commentId}:
    put:
      summary: Update a comment
      description: Update an existing comment for a post
      parameters:
        - name: postId
          in: path
          description: ID of the post
          required: true
          type: integer
        - name: commentId
          in: path
          description: ID of the comment
          required: true
          type: integer
      responses:
        '200':
          description: Comment updated successfully
definitions:
  Post:
    type: object
    properties:
      postId:
        type: integer
      postedBy:
        type: integer
      image:
        type: string
      description:
        type: string
      createdAt:
        type: string
        format: date-time
      comments:
        type: array
        items:
          $ref: '#/definitions/Comment'
  Comment:
    type: object
    properties:
      commentId:
        type: integer
      createdAt:
        type: string
        format: date-time
      userId:
        type: integer
      comment:
        type: string
